export default[
    {
        path:'/Waitstaff',
        name:'Waitstaff',
        component:()=>import('../views/staff/pages/WaitstaffDashboard.vue'),
        meta:{
            requireAuth:true,
            roles:['waitstaff']
        }
    },
    {
        path:'/Kitchen',
        name:'kitchen',
        component:()=>import('../views/staff/pages/KitchenDashboard.vue'),
        meta:{
            requireAuth:true,
            roles:['Kitchen']
        }
    },
    {
        path:'/Bar',
        name:'bar',
        component:()=>import('../views/staff/pages/BarDashboard.vue'),
        meta:{
            requireAuth:true,
            roles:['Bar']
        }
    },
    {
        path:'/Casher',
        name:'casherReceipts',
        component:()=>import('../views/staff/pages/CasherReceipts.vue'),
        meta:{
            requireAuth:true,
            roles:['Casher']
        }
    },
]